apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-secrets-abilities
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
- apiGroups: [""]
  resources: 
  - serviceaccounts
  verbs:
  - create
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources: 
  - rolebindings
  - roles
  verbs:
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-role-list-pods
  namespace: test
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-cluster-role-list-pods
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
