name: Tests

on: [push, workflow_dispatch]

jobs:
  fmtcheck:
    runs-on: ubuntu-latest
    env:
      GOFUMPT_VERSION: 0.3.1
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version-file: .go-version
      - run: |
          go install "mvdan.cc/gofumpt@v${GOFUMPT_VERSION}"
          make fmtcheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version-file: .go-version
      - run: make test

  integrationTest:
    runs-on: ubuntu-latest
    needs: [fmtcheck, test]
    strategy:
      fail-fast: false
      matrix:
        kind-k8s-version: [1.23.17, 1.24.13, 1.25.9, 1.26.4, 1.27.2]
        enterprise: ["", "-ent"]
    name: Integration test ${{ matrix.enterprise }} kind ${{ matrix.kind-k8s-version }}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Create K8s Kind Cluster
        uses: helm/kind-action@fa81e57adff234b2908110485695db0f181f3c67 # v1.7.0
        with:
          version: v0.19.0
          cluster_name: vault-plugin-secrets-kubernetes
          config: integrationtest/kind/config.yaml
          node_image: kindest/node:v${{ matrix.kind-k8s-version }}
          kubectl_version: v1.25.3
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version-file: .go-version
      - env:
          VAULT_LICENSE_CI: ${{ secrets.VAULT_LICENSE_CI }}
        run: make setup-integration-test${{ matrix.enterprise }}
      - env:
          INTEGRATION_TESTS: true
        run: make integration-test TESTARGS="-v"
